---

name: build proof-of-concept
on:
  push:
    branches: 
      - **

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2.4.0

